#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=new
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --time=00:30:00
#SBATCH --output=./output/array_%A.out
#SBATCH --error=./output/array_%A.err

module purge
module load 2023
module load Anaconda3/2023.07-2
module load openai


cd Video-LLaVA

source activate videollava

CUDA_VISIBLE_DEVICES=0 bash scripts/v1_5/eval/run_qa_activitynet.sh

bash scripts/v1_5/eval/eval_qa_activitynet.sh