#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gpus=2
#SBATCH --job-name=anet_f
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --time=10:00:00
#SBATCH --mem=120G
#SBATCH --output=./output/array_%A.out
#SBATCH --error=./output/array_%A.err

module purge
module load 2022
module load Anaconda3/2022.05
module load FFmpeg/4.4.2-GCCcore-11.3.0

source activate vast

cd $HOME/github/VAST

sh ./scripts/finetune_anet.sh